command_history = [ 'help', 'save' ]
log_history = [
    [ '[29-08-2025 12:50:35] [      LOAD] [  DEBUG]: Loading Game Settings From TOML', 0.0, 1.0, 1.0, 1.0 ],
    [
        '[29-08-2025 12:50:35] [      TOML] [    LOG]: [*] Loading game settings from "settings/main.toml"',
        1.0,
        1.0,
        1.0,
        1.0
    ],
    [ '[29-08-2025 12:50:35] [      TOML] [    LOG]:     [-] Loading console settings from toml', 1.0, 1.0, 1.0, 1.0 ],
    [ '[29-08-2025 12:50:35] [      TOML] [    LOG]:     [-] Loading key bindings from toml', 1.0, 1.0, 1.0, 1.0 ],
    [
        '[29-08-2025 12:50:35] [      TOML] [    LOG]:     [-] Loading graphics settings from toml',
        1.0,
        1.0,
        1.0,
        1.0
    ],
    [ '[29-08-2025 12:50:35] [      LOAD] [  DEBUG]: Loading Gameplay Data', 0.0, 1.0, 1.0, 1.0 ],
    [ '[29-08-2025 12:50:35] [      TOML] [    LOG]: Loading cards.', 1.0, 1.0, 1.0, 1.0 ],
    [ '[29-08-2025 12:50:35] [      TOML] [    LOG]: (*) Loaded 2 cards from TOML.', 1.0, 1.0, 1.0, 1.0 ],
    [
        "[29-08-2025 12:50:35] [      TOML] [  DEBUG]:     [-] Card{id: 0, name: 'The First Nap', description: 'Sleep.', baseColor: 1.000000, 0.000000, 1.000000, 1.000000, texturePath: 'NULL', attack: 1, defense: 1, speed: 10, gameplayText: 'Gotta sleep sometime.'}",
        0.0,
        1.0,
        1.0,
        1.0
    ],
    [
        "[29-08-2025 12:50:35] [      TOML] [  DEBUG]:     [-] Card{id: 1, name: 'A Brief Respite', description: 'Rest.', baseColor: 1.000000, 0.000000, 1.000000, 1.000000, texturePath: 'NULL', attack: 1, defense: 1, speed: 10, gameplayText: 'Relax and take things in.'}",
        0.0,
        1.0,
        1.0,
        1.0
    ],
    [ '[29-08-2025 12:50:35] [      LOAD] [  DEBUG]: Loaded 2 cards from cards/cards.toml', 0.0, 1.0, 1.0, 1.0 ],
    [ '[29-08-2025 12:50:35] [      LOAD] [  DEBUG]: Initializing Window', 0.0, 1.0, 1.0, 1.0 ],
    [ '[29-08-2025 12:50:35] [      LOAD] [  DEBUG]: Initializing Vulkan', 0.0, 1.0, 1.0, 1.0 ],
    [
        '[29-08-2025 12:50:36] [    VULKAN] [  DEBUG]: Validation Layer info message windows_get_device_registry_files: GUID for 4 is not SoftwareComponent skipping',
        0.0,
        1.0,
        1.0,
        1.0
    ],
    [
        '[29-08-2025 12:50:36] [    VULKAN] [  DEBUG]: Validation Layer info message windows_get_device_registry_files: GUID for 5 is not SoftwareComponent skipping',
        0.0,
        1.0,
        1.0,
        1.0
    ],
    [
        '[29-08-2025 12:50:36] [    VULKAN] [  DEBUG]: Validation Layer info message Searching for ICD drivers named .\igvk64.dll',
        0.0,
        1.0,
        1.0,
        1.0
    ],
    [
        '[29-08-2025 12:50:36] [    VULKAN] [  DEBUG]: Validation Layer info message Searching for ICD drivers named .\nvoglv64.dll',
        0.0,
        1.0,
        1.0,
        1.0
    ],
    [ '[29-08-2025 12:50:36] [      LOAD] [  DEBUG]: Initializing Dear ImGui', 0.0, 1.0, 1.0, 1.0 ],
    [
        '[29-08-2025 12:50:36] [      LOAD] [    LOG]: Acquired texture: "images/splash.png", size 1920 x 1080',
        1.0,
        1.0,
        1.0,
        1.0
    ],
    [
        '[29-08-2025 12:50:36] [      LOAD] [    LOG]: Splash messages loaded from "text/loading.toml"',
        1.0,
        1.0,
        1.0,
        1.0
    ],
    [ '[29-08-2025 12:50:50] [          executeCommand] [    LOG]:  Executing Command: help', 1.0, 1.0, 1.0, 1.0 ],
    [ '> help - available commands are: help, clear, history', 1.0, 1.0, 1.0, 1.0 ],
    [ '> clear - clears the console', 1.0, 1.0, 1.0, 1.0 ],
    [ '> history - shows command history', 1.0, 1.0, 1.0, 1.0 ],
    [ '> !<number> - repeat command number from history', 1.0, 1.0, 1.0, 1.0 ],
    [ '[29-08-2025 12:50:56] [          executeCommand] [    LOG]:  Executing Command: help', 1.0, 1.0, 1.0, 1.0 ],
    [ '> help - available commands are: help, clear, history', 1.0, 1.0, 1.0, 1.0 ],
    [ '> clear - clears the console', 1.0, 1.0, 1.0, 1.0 ],
    [ '> history - shows command history', 1.0, 1.0, 1.0, 1.0 ],
    [ '> !<number> - repeat command number from history', 1.0, 1.0, 1.0, 1.0 ],
    [ '[29-08-2025 12:50:57] [          executeCommand] [    LOG]:  Executing Command: save', 1.0, 1.0, 1.0, 1.0 ]
]