[Console]
WarningColor = [1.0, 1.0, 0.0, 1.0]
ErrorColor = [1.0, 0.0, 0.0, 1.0]
LogColor = [1.0, 1.0, 1.0, 1.0]
DebugColor = [0.2, 1.0, 1.0, 1.0]
MainConsoleBgColor = [0.2, 0.2, 0.2, 1.0]

[Display]
Size = [1000, 800]
Pos = [40, 40]

[KeyBindings]
ToggleSettingsKey = "Escape"
ToggleUiKey = "F2"
ToggleStatsKey = "F3"
ToggleConsoleKey = "Backslash"
