
# a card is an array
# ID
# card name
# base color
# texture
# attack
# defense
# speed
# gameplay text
# descriptive text

DreamCards = [
    [0, "The First Nap", [1.0, 0.0, 1.0, 1.0], "NULL", 1, 1, 10, "Sleep.", "Gotta sleep sometime."],
    [1, "A Brief Respite", [1.0, 0.0, 1.0, 1.0], "NULL", 1, 1, 10, "Rest.", "Relax and take things in."]
]

# A Brief Respite


#champions: The Mother, The Child
Champions = [
    [0, "The Mother", "Pronounced dead at birth.\nLeft for dead by her friends.\nAfter defeating death twice,\nand surviving untold demons,\nshe has survived for one purpose.\n She will do anything to protect you."],
    [1, "The Intellect", "A beneficiary of privilege.\nWise and mature beyond their years.\nNever hesitates to dispense justice.\nNever hesitates to share wealth.\nWill do anything to fight the demons and protect the innocent."],
]