name: Discord Notifications

on:
  push:
    branches:
      - main # or your default branch

jobs:
  notify-discord:
    runs-on: self-hosted
    steps:
      - name: Send Discord notification
        uses: rjstone/discord-webhook-notify@v2 # or v2 for latest features
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_SECRET_FOR_COMMITS_TO_DISCORD_MSGS }}
          username: ${{ github.event.head_commit.author.name  }}
          avatarUrl: http://shaunramsey.com/whitesquared.png
          text: |

            ${{ github.event.head_commit.author.name }} posted a new commit in `${{ github.repository }}`:
            >>> ``` -[View Commit](${{ github.event.head_commit.url }})
            ${{ github.event.head_commit.message }}
            ```
          flags: SuppressNotifications
          # severity: info
          # footer: New commit in ${{ github.repository }}
          # description: |
          # Author: ${{ github.event.head_commit.author.name }}
          # Commit message: ```diff
          # ${{ github.event.head_commit.message }}
          # ```
          # [View Commit](${{ github.event.head_commit.url }})
